version: '2.2'
services:
  influxdb-singleton:
    image: influxdb:2.0
    container_name: influxdb-singleton
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=123456
    volumes:
      - ./influxdb2:/var/lib/influxdb2
      - ./config.yml:/etc/influxdb2/config.yml
    ports:
      - 8086:8086
    networks:
      - local-net

networks:
  local-net:
    external: true